-- based on: https://github.com/LunarVim/Neovim-from-scratch
require "user.options"
require "user.whichkey"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.project"
